/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import com.kotlindiscord.kord.extensions.ExtensibleBot
import template.extensions.TestExtension

@Suppress("UnderscoresInNumericLiterals")  // It's an ID
const val TEST_SERVER_ID = 787452339908116521  // Change this to your test server's ID

private val TOKEN = System.getenv("TOKEN")

suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        commands {
            defaultPrefix = "?"
            slashCommands = true

            prefix { default ->
                if (guildId?.value == TEST_SERVER_ID) {
                    // For this server, we use ! as the command prefix
                    "!"
                } else {
                    default
                }
            }
        }

        extensions {
            add(::TestExtension)
        }
    }

    bot.start()
}
