/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.quiltmc.community

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kordex.ext.mappings.extMappings
import org.quiltmc.community.extensions.SyncExtension
import org.quiltmc.community.extensions.messagelog.MessageLogExtension

suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        messageCommands {
            defaultPrefix = "?"

            check { it.message.author != null }
        }

        extensions {
            add(::MessageLogExtension)
            add(::SyncExtension)

            extMappings {}
        }
    }

    bot.start()
}
